namespace CommonInteraction
{
    public enum AnswerType
    {
        GameStarted,
        MafiaWins,
        PeacefulWins,
        SuccessfullyRegistered,
        AlreadyRegistered,
        SuccessfullyVoted,
        AlreadyVoted,
        EndDay,
        EndNight,
        DayKill,
        DayAllAlive,
        NightKill,
        NightAllAlive,
        NewGame,
        YouAreMafia,
        YouArePeaceful,
        OnlyInLocal,
        OnlyInCommon,
        GameIsGoing,
        NeedMorePlayers,
        YouAreNotInGame,
        YouCantVoteThisPl,
        YouCantKillThisPl,
        NotTimeToVote,
        NotTimeToKill,
        EnterNumber,
        IncorrectNumber,
        YouAreNotMafia,
        SuccessfullyKilled,
        AlreadyKilled,
        NeedToCreateGame,
        MafiaKilling,
        IncorrectVote
    }
}